name: MacOS build process
on:
  workflow_call:
    inputs:
      build_type:
        required: true
        type: string
      is_qt_cached:
        required: true
        type: boolean

jobs:
  macos:
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: macos-14
            name: macOS
            macosx_deployment_target: 11.0
            qt_ver: 6
            qt_host: mac
            qt_arch: ""
            qt_version: "6.8.1"
            qt_modules: "qt5compat qtimageformats qtnetworkauth"
    env:
      MACOSX_DEPLOYMENT_TARGET: ${{ matrix.macosx_deployment_target }}
      INSTALL_DIR: "install"
      BUILD_DIR: "build"
      CCACHE_VAR: ""
      HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set short version
        shell: bash
        run: |
          ver_short=`git rev-parse --short HEAD`
          echo "VERSION=$ver_short" >> $GITHUB_ENV

      - name: Install Dependencies (macOS)
        run: |
          brew update
          brew install ninja extra-cmake-modules

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          aqtversion: "==3.1.*"
          py7zrversion: ">=0.20.2"
          version: ${{ matrix.qt_version }}
          target: "desktop"
          arch: ${{ matrix.qt_arch }}
          modules: ${{ matrix.qt_modules }}
          cache: ${{ inputs.is_qt_cached }}

      - name: Setup java (macOS)
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Configure CMake (macOS)
        if: matrix.qt_ver == 6
        run: |
          cmake -S . -B ${{ env.BUILD_DIR }} -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_DIR }} -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} -DENABLE_LTO=ON -DLauncher_ENABLE_JAVA_DOWNLOADER=ON -DLauncher_BUILD_PLATFORM=official -DCMAKE_C_COMPILER_LAUNCHER=${{ env.CCACHE_VAR }} -DCMAKE_CXX_COMPILER_LAUNCHER=${{ env.CCACHE_VAR }} -DLauncher_QT_VERSION_MAJOR=${{ matrix.qt_ver }} -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -G Ninja

      - name: Build
        run: |
          cmake --build ${{ env.BUILD_DIR }}

      - name: Test
        run: |
          ctest -E "^example64|example$" --test-dir build --output-on-failure

      - name: Package (macOS)
        run: |
          cmake --install ${{ env.BUILD_DIR }}
          cd ${{ env.INSTALL_DIR }}
          chmod +x "HalkyLauncher.app/Contents/MacOS/halkylauncher"
          sudo codesign --sign "-" --deep --force --options runtime "HalkyLauncher.app/Contents/MacOS/halkylauncher"
          mv "HalkyLauncher.app" "Halky Launcher.app"
          ditto -c -k --sequesterRsrc --keepParent "Halky Launcher.app" ../HalkyLauncher.zip

      - name: Upload binary tarball (macOS)
        uses: actions/upload-artifact@v4
        with:
          name: HalkyLauncher-${{ matrix.name }}-${{ env.VERSION }}-${{ inputs.build_type }}
          path: HalkyLauncher.zip
