name: Publish

on:
  release:
    types: [ released ]

permissions: { }

jobs:
  winget:
    name: Winget

    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Publish on Winget
        uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: HalkyLauncher.HalkyLauncher
          version: ${{ github.event.release.tag_name }}
          installers-regex: 'HalkyLauncher-Windows-MSVC(:?-arm64|-Legacy)?-Setup-.+\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
