name: Publish to WinGet

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@v2
        with:
          identifier: HalkyLauncher.HalkyLauncher
          installers-regex: 'HalkyLauncher-Windows-MSVC-Setup-.*\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
